### ISSUE TITLE
Mapping - Organisations responsables

### ISSUE THREAD

**Issue by MarieLambois** [cnigfr/metadonnee#2]
Le contenu est défini [ici](https://github.com/cnigfr/metadonnee/blob/main/MappingINSPIRE-DCAT/OrganisationResp). 
Des commentaires ?

**Comment by jerbou** [comment]
Pour moi, le lien est en 404 (https://github.com/cnigfr/metadonnee/blob/main/MappingINSPIRE-DCAT/OrganisationResp)

A corriger peut être par :
https://github.com/cnigfr/metadonnee/blob/main/MappingINSPIRE-DCAT/OrganisationResp.md

le .md (qui serait passé à la trappe).
