### ISSUE TITLE
Mapping - Classification des données

### ISSUE THREAD

**Issue by MarieLambois** [cnigfr/metadonnee#8]
<h3><a name="md-on-md">Classification des données</a></h3>
<p>Le contenu est défini ici : https://github.com/cnigfr/metadonnee/blob/main/MappingINSPIRE-DCAT/Classification.md</p>

Des commentaires ?

**Comment by yvanlebras** [comment]
Here, this is related to "Thèmes INSPIRE" isn't it ? So maybe more to dcat:theme ?

**Comment by MarieLambois** [comment]
Ce champ correspond à Topic category (de l'ISO 19115). A discuter.

**Comment by alhyss** [comment]
J'ai aussi une nette préférence pour `dcat:theme`. C'est la propriété recommandée par DCAT pour représenter toutes les classifications thématiques, revenir à une propriété parente plus générique juste pour cette classification thématique-là me semble être l'une des mauvaises idées de GeoDCAT-AP.

J'imagine que l'objectif était d'avoir deux propriétés différentes pour les thèmes INSPIRE et les thèmes ISO, mais: 
- Il est inutile de faire porter cette distinction par la propriété qui introduit le concept alors que la propriété `skos:inScheme` du concept le fait déjà très bien.
- Ça devient totalement inefficace dès lors que d'autres classifications thématiques sont également utilisées, puisqu'il faudra aussi les mapper vers l'une de ces propriétés.
- Sur le fond, je ne vois aucune raison qui rendrait `dcat:theme` inadaptée aux thèmes ISO. C'est une classification thématique très comparable à [celle de l'opendata européen](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/data-theme).
- Utiliser deux propriétés différentes pour représenter deux informations de même nature pose un problème de lisibilité.
- Si les thèmes de la nomenclature ISO sont introduits par `dct:subject`, alors il ne sera pas possible d'utiliser [`dcat:themeTaxonomy`](https://www.w3.org/TR/vocab-dcat-3/#Property:catalog_themes) pour déclarer cette nomenclature comme l'une des classifications thématiques de référence pour le catalogue.

La seule raison que je verrais de considérer l'usage `dct:subject` serait l'interopérabilité. C'est une extension de DCAT, ce qui est a priori défavorable de ce point de vue, mais la balance pourrait s'inverser si beaucoup de catalogues ont déjà adopté cette pratique.
